### PR TITLE
feat/css-variables-first-draft

### PR DESCRIPTION
**Pull request by moT01**
Initial commit of CSS variables project. Any feedback is welcome.

issue #130

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
Wow 100 challenges?! Great work; this is going to take some serious time to review.

**Comment by moT01** [comment]
Yea, I got a little worried about the length as I was getting deep into it. I would have made a few less buildings if I could start over, but it's really difficult to go back and make a large change like that.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, took a quick look at your draft here and it's looking great! As you mentioned, you could simplify the project a bit by removing some buildings, but I understand how time consuming it can be to go back and change all of these files. It shouldn't be a problem so long as the broken down project is less than 200 tests.

I just noticed a couple of things. First, the class names could be more descriptive. I know that they're abbreviations for background building or foreground building and their sections, but it might be better to teach users to favor longer, easier to read class names. This is a pretty minor detail for now and can be changed later. 

Next, each challenge will only test one thing, so files like `index030.html` could be broken down into two steps: one for using the `*` and applying a border, and another for applying `box-sizing: border-box;`. You could also go back and break adding the doctype, head, html, and body tags into different steps, but I don't think it's really necessary. Starting with the skeletal HTML page and having the user add the title as a first step is fine, too.

**Comment by moT01** [comment]
Thanks for the feedback @scissorsneedfoodtoo. So are you kind of saying that most of the challenges need to be broken up? 

Like `index050`, for instance, should be three challenges? One to create a div with the class, one for adding a width, and one for adding a height?

I pretty much did some stuff like that on every challenge that could be broken up. I thought that someone who has done the basic html and css should be able to pretty easily add elements and give them a few small properties. Breaking all those up would lead to many repetitive width and height challenges and would definitely go beyond the 200.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, I'm sorry, I could have explained this better. You make a good point that the users probably would have finished the basic HTML and CSS projects by the time they're working on this one. Though it's my understanding that we'll want to break things as much as possible, you're right in thinking it would be tedious after a certain point.

Looking at the RPG game as an example, from `index010` to `index050` users declare variables one at a time, then in `index060` declare two variables. And in `index120`, users are asked to declare nine different variables using `querySelector()`. I suppose it would be more accurate to say that we should break things down into small steps when first introducing something, then expect more as users are familiar with what you want them to do.

I think for your project it would be good to start a bit slower as users build the first building, then quickly ramp up since the other buildings share a similar foundation (no pun intended). For example, in `index050` it might be good to have users create the `div` element and give it a class. Then in the next lesson (`index051`?), users can target the `background-buildings` class and give it a width and height of 100%. I could also see breaking `index060` into two steps, first to nest the `div` and give it a class, then to set its width and height. Once you get to `index070` and `index080`, they should know what to do, so there's no need to break those lessons down. Also, since you teach very useful techniques in `index030` and `index040` that have a big impact on the look of the page, so it might be good to break those down into two or three lessons apiece.

Hope that helps! You have a really cool project here and I can't wait to build a city skyline myself.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, just wanted to check in and see how everything's going. If you don't mind, I'll merge this and you can submit another PR to continue your work.

**Comment by moT01** [comment]
I haven't really done anything since the PR. Yes, you can go ahead and merge it if you want and I'll just make another PR.

**Comment by scissorsneedfoodtoo** [comment]
Great! I'll do that now.

**Pull request merged**
