### PR TITLE
feat: add regex lab

### LINKED ISSUE #458: chore: add lab for regex in frontend cert
We need a lab for them to do on Regular expressions.
Here is the workshop they will do before this
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-regular-expressions-by-building-a-spam-filter/step-35

They will also know all of the fundamentals (strings, functions, objects, arrays, etc)
They will also know about higher order functions like map, filter, reduce.
And they will know DOM basics like getElementById, querySelector, querySelectorAll, click events, change events. 

## Acceptance criteria

- [ ] create a new folder of the project in the `frontend-cert/js-projects` directory
- [ ] add your completed project in an `script.js` file in that new folder
- [ ] create a markdown file for your proposed user stories. You should call it `user-stories.md` and place it in your new project folder

### PR DESCRIPTION
**Pull request by Dario-DC**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes ####

image

### CODE REVIEW

**Comment by moT01** [comment]
Is this one ready?

**Comment by zairahira** [comment]
@Dario-DC 
I am not sure if `matchAll` has been taught yet. I see `match` in the sheet.
I would suggest to include `matchAll` in the lecture videos and keep this project as it is quite appropriate for this lab.

The same goes for `replaceAll`, I couldn't find it in the sheet.

**Comment by Dario-DC** [comment]
> @Dario-DC I am not sure if `matchAll` has been taught yet. I see `match` in the sheet. I would suggest to include `matchAll` in the lecture videos and keep this project as it is quite appropriate for this lab.
> 
> The same goes for `replaceAll`, I couldn't find it in the sheet.

They've been added to the lecture scripts.

**Review by moT01 — COMMENTED** [review]
This is an interesting looking project, looks pretty fun - but I'm wondering if it's aligned with what we want it to teach. I don't really see a whole lot of regex that users have to write here.

Wondering if we should try to come up with something else?

**Comment by Dario-DC** [comment]
I had the same doubts. I'll try to come up with something else that require campers to write regular expressions.

Do you think this could be used in any other sections of the curriculum? @moT01

**Comment by Dario-DC** [comment]
Some time ago Zaira suggested to code a tool that scans a markdown file and extracts every link. This could be an idea. The markdown could be provided as a string in the seed code. What do you think? @moT01

**Comment by moT01** [comment]
> Do you think this could be used in any other sections of the curriculum?

Probably. There's a number of things it covers.

> a tool that scans a markdown file and extracts every link

That's not bad, but I think you might only need to write one regex for that. Which works. But maybe something where they need to write several. I asked GPT for a list of ideas, here's a few that sound pretty decent:

Log File Analyzer: Create a script that parses a log file and extracts information like IP addresses, dates, or error messages using regex.

Simple Markdown Parser: Build a basic parser that converts simple markdown (like **bold**, *italic*, and # heading) into HTML using regex.

Password Strength Indicator: Create a password strength meter that evaluates a password based on criteria like the presence of uppercase letters, numbers, special characters, etc., using regex.

Form Validator: Create a form with fields like email, phone number, and zip code. Use regex to validate the input before submission.

I like the first two.

**Comment by Dario-DC** [comment]
>That's not bad, but I think you might only need to write one regex for that.

That's true. I like the markdown parser. I'll update this PR as soon as I have something that works.

The form validator would be for another lab.

**Comment by moT01** [comment]
So we will need to update the order of the blocks on there as well as in the repo. I will see if I can come up with a script to update the repo.

**Review by moT01 — APPROVED** [review]

**Pull request merged**
