### PR TITLE
feat: add lunch picker lab (JS only)

### LINKED ISSUE #428: chore: add lab for arrays to frontend cert (JS only)
There will be a workshop and lab that will teach campers about arrays and basic array methods.
We need a lab project for them to do right after the workshop.

Campers will know the following so far:

- let
- const
- assignment
- reassignment
- basic string usage
- console.log
- camelCase
- string concatenation using the + operator
- template literals
- str.length property
- bracket notation and retrieving characters from strings
- str.indexOf method
- if/else
- Number()
- Math.floor
- Math.random
- getting a random number from a range
- prompt()
- ===
- if/else if/else
- true and false (truthy and falsey)
- comparison operators
- array basics
- push
- pop
- shift
- unshift

## Acceptance criteria

- [ ] create a new folder of the project in the `frontend-cert/js-projects` directory
- [ ] add your completed project in an `script.js` file in that new folder
- [ ] create a markdown file for your proposed user stories. You should call it `user-stories.md` and place it in your new project folder

### PR DESCRIPTION
**Pull request by zairahira**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #428

### CODE REVIEW

**Review by Dario-DC — COMMENTED** [review]
I think this could work. But what if we ask to change the `meals` array in some way instead?
Something like pushing another couple of elements to the array (let's say they're the daily specials, for example) and/or removing the chosen element. Not sure if they know how to remove elements by index or value, yet.

**Comment by zairahira** [comment]
According to the sheet, the array methods like removing and adding elements come after this lab.
However, at this point campers would know how to access and update items. Should I make changes according to that?

**Comment by Dario-DC** [comment]
There's a mismatch between the issue related to this PR and the sheet apparently. Unless the array methods are going to be introduced in the previous workshop (which I think has not been created yet) and then taught in the following videos.

Is that possible? @zairahira @jdwilkin4

**Comment by jdwilkin4** [comment]
I went ahead and updated it on the sheet.
So push, pop, shift and unshift will be taught before this in the lecture block

**Comment by jdwilkin4** [comment]
I just added the workshop PR that will go before this lab

https://github.com/freeCodeCamp/CurriculumExpansion/pull/495

**Comment by zairahira** [comment]
@Dario-DC I have added a few more methods like `push()` and `pop()`. Let me know what you think of this one.

**Comment by moT01** [comment]
Just throwing out ideas - you could start with an empty array, or maybe just one item in it, and have them push several more instead of just one.

"You should create a `adultsMenu` array with one item, "Salad", in it.
"You should use "push" to add three more food items to the `adultsMenu` array"
"You should create a `kidsMenu` array with one item, "Pizza", in it.
"You should use "push" to add two more food items to the `kidsMenu` array"

**Comment by zairahira** [comment]
@moT01 I have added a few more stories as suggested. Let me know what you think.

**Review by Dario-DC — COMMENTED** [review]
Sorry Zaira, I missed your comment. I think it works well :+1:

**Review by moT01 — APPROVED** [review]

**Pull request merged**
