### PR TITLE
chore: add Learn Pseudo-classes workshops

### LINKED ISSUE #421: chore: add Learn Pseudo-classes workshops to frontend cert
In this new frontend cert, we have module to go into more detail about pseudo classes and how the different ones work. The preceding lecture block will teach them about the different types of pseudo classes.

The cafe menu does introduced pseudo classes briefly here
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-91

But we will need a small workshop for campers to apply what they learned about pseudo classes in a step based tutorial.

## Acceptance criteria

- [ ] create a new folder of the project in the `frontend-cert/css-projects` directory
- [ ] add your completed project(index.html and styles.css files) in that new folder

### PR DESCRIPTION
**Pull request by larymak**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #421

### CODE REVIEW

**Comment by jdwilkin4** [comment]
I have concerns that this will be to similar to the build a personal portfolio page that they have to build.
Cane we change this to something else?

**Comment by larymak** [comment]
> I have concerns that this will be to similar to the build a personal portfolio page that they have to build. Cane we change this to something else?

Can I replace it with a Portfolio gallery?

**Comment by jdwilkin4** [comment]
will the portfolio gallery be different then the flexbox workshop we are adding?
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-24

If the projects are different enough, then that should be fine. otherwise, you will need to find another option. Remember that Tom created that sheet of project ideas. so you can look to that if you need ideas, or message the team for potential ideas 👍

**Comment by larymak** [comment]
> will the portfolio gallery be different then the flexbox workshop we are adding? https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-24
> 
> If the projects are different enough, then that should be fine. otherwise, you will need to find another option. Remember that Tom created that sheet of project ideas. so you can look to that if you need ideas, or message the team for potential ideas 👍

Updated with a project from the suggestion list Greeting Card project

**Review by jdwilkin4 — COMMENTED** [review]
This looks good.
A few things

no1: you shouldn't use pixels for font sizes. campers will have learned about ems and rems in the previous module. So you will need to fix that in the css.

no.2: campers will not have learned about hex values yet. that is in the next module. so you can only use named colors. please update that

**Review by jdwilkin4 — APPROVED** [review]
Looks good

**Pull request merged**
