### PR TITLE
feat: restructure files

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

This PR accomplishes 3 things:

- Organise projects based on teh superblock they are in
- Name project directories to reflect name in spreadsheet
- Move projects that cannot be mapped to spreadsheet to `unplanned` directory

My hope is that this makes it easier to track what projects are completed and which need to be prototyped, as well as finding a project to break down into steps.

It's big, but the only deletion was a duplicate of the dice game (I know Jessica rewrote that).

### CODE REVIEW

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
This looks good.
Thanks for doing this

My only suggestion would be to move the following projects into the JS superblock folder
- decimal-to-binary
- intermediate-algorithm-scripting
- javascript-calorie-counter
- learn-array-methods-by-building-stats-calculator
- learn-JSON-fetch-promises...
- music-playlist-app

**Comment by naomi-lgbt** [comment]
Thanks for catching those~! I didn't realise how far behind my branch was lol

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
I was able to cross reference this list with the spreadsheet and we just need to update a few things but otherwise we will be good to go. 👍 

For the learn data structures by building a shopping cart project, we need to replace the old project that is there with the updated [one](https://github.com/freeCodeCamp/CurriculumExpansion/tree/main/learn-data-structures-by-building-a-shopping-cart) that was merged a few weeks ago

For the sports team project, we need to replace the old one with steps with this new [one](https://github.com/freeCodeCamp/CurriculumExpansion/tree/main/json-sports-team) here that was merged a few months back. 

For the regex spam filter project, we need to replace the old one with steps with this new [one](https://github.com/freeCodeCamp/CurriculumExpansion/tree/main/learn-regular-expressions-by-building-a-spam-filter) here

**Comment by naomi-lgbt** [comment]
It looks like the main files were correct - the step files were outdated and have been removed.

**Review by jdwilkin4 — APPROVED** [review]
Looks good 👍

**Review by scissorsneedfoodtoo — COMMENTED** [review]
Thanks again for taking the time to organize all of this @naomi-lgbt. It will make it much easier to find the correct prototype.

Took a look locally and everything looks good.

The only thing I noticed is that `learn-array-methods-by-building-a-statistics-calculator` is in the root directory.

Once that's moved to the `javascript-algorithms-and-data-structures` directory, we should be good to go.

**Comment by naomi-lgbt** [comment]
Moved~!

**Comment by scissorsneedfoodtoo** [comment]
Everything LGTM 👍 

Thanks again for taking the time to do all of this @naomi-lgbt 🎉

**Pull request merged**
