### PR TITLE
feat: add hmtl video lab

### LINKED ISSUE #382: chore: add HTML only video page project to frontend cert
The basic HTML section will have a few labs for campers to do.
Labs are defined as short projects campers build on their own. It will consist of a blank editor and user stories.
Here is an example for the format:
https://www.freecodecamp.org/learn/the-odin-project/top-build-a-recipe-project/top-build-a-recipe-project

In the previous section of the course, campers will have learned about working with audio and videos. So they will have learned how to work with iframes and embedding videos onto a page.

For this issue, we need a lab that covers the following basic HTML topics: 

- headings
- images(optional)
- paragraphs
- main element
- section elements 
- iframes for freeCodeCamp YouTube videos

## Note about length of project

This is still early on in the cert.
So this should still be a smaller scale project.
So we could probably just have them add maybe 3-4 videos on the page.

## Note about adding new images

For adding new images, make sure they are free to use. You will also need to be add that image to our CDN repo here
https://github.com/freeCodeCamp/cdn

Once the new image has been added to the CDN repo, then you will need to reference that cdn link in your project.

If you are not sure about if an image can be used, reach out on staff chat. 

## Acceptance criteria

- [ ] create a new folder of the project in the `frontend-cert/html-projects` directory
- [ ] add your completed project in an `index.html` file in that new folder
- [ ] create a markdown file for your proposed user stories. You should call it `user-stories.md` and place it in your new project folder

### PR DESCRIPTION
**Pull request by Dario-DC**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #382

I'm not sure about what we want to add here, but I think that we can ask campers to create a page that embeds video lectures from the upcoming frontend certification.

### CODE REVIEW

**Comment by jdwilkin4** [comment]
I was thinking we could use videos from our youtube page
https://www.youtube.com/c/Freecodecamp

hundreds of options to choose from there

**Comment by jdwilkin4** [comment]
> embeds video lectures from the upcoming frontend certification.

I am not sure how long it will take for the upcoming frontend cert videos to be made available.
So using fcc youtube videos will be a better choice because it won't block this project from being added to the superblock in the short term

**Review by moT01 — COMMENTED** [review]
Looking good @Dario-DC 👍 

Couple minor typos.

Only other suggestion would be to give the iframes size properties cause they're kind of small:

`<iframe width="560" height="315" src="https://www.youtube.com/embed/7K6bCewZzJU?si=gCcenfsrI0mH_h0m"></iframe>`

But maybe that isn't really taught before this. Pretty simple things to figure out though.

**Comment by jdwilkin4** [comment]
iframe sizes will be taught in the lecture videos so it is fine to include it here

**Comment by bbsmooth** [comment]
I would add one thing for accessibility. The `iframe` element must have an accessible name to meet WCAG requirements. Usually this is done by adding the `title` attribute to the `iframe` element, which is what I would recommend here. In this case, because these are going to be videos, the `title` attribute would probably be the title of the video with the word "video" at the end.

**Comment by moT01** [comment]
LGTM if this is ready @Dario-DC 👍 

Name suggestion: Video Compilation Page

**Comment by Dario-DC** [comment]
> LGTM if this is ready @Dario-DC 👍
> 
> Name suggestion: Video Compilation Page

Done :+1:

**Comment by moT01** [comment]
Just to clarify, I meant that we could call it `Video Compilation Page` on the main site. Then users can make it a freeCodeCamp videos page, or a bike riding videos page.

**Pull request merged**
