### PR TITLE
feat: add styling forms lab 

### LINKED ISSUE #396: chore: add styling forms lab project to frontend cert
The Styling forms module will have a few labs for campers to do.
Labs are defined as short projects campers build on their own. It will consist of a blank editor and user stories.
Here is an example for the format:
https://www.freecodecamp.org/learn/the-odin-project/top-build-a-recipe-project/top-build-a-recipe-project

The previous workshop will have been the registration form project here
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-65

So we need a lab that covers some of those topics in that workshop.

For this lab, we want to have a few user stories focused on adding styles to forms.

## length of project

Maybe 10-15 user stories?

## note about the HTML boilerplate

At this point in the cert, campers will have created a few labs and worked on a few workshops.
So we no longer need to force them to write out the HTML boilerplate each time.
So we don't need to create user stories for the HTML boilerplate anymore. 

## Note about adding new images

For adding new images, make sure they are free to use. You will also need to be add that image to our CDN repo here
https://github.com/freeCodeCamp/cdn

Once the new image has been added to the CDN repo, then you will need to reference that cdn link in your project.

If you are not sure about if an image can be used, reach out on staff chat. 

## Acceptance criteria

- [ ] create a new folder of the project in the `frontend-cert/css-projects` directory
- [ ] add your completed project in an `index.html` file and `styles.css` file in that new folder
- [ ] create a markdown file for your proposed user stories. You should call it `user-stories.md` and place it in your new project folder

### PR DESCRIPTION
**Pull request by ihechikara**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #396

### CODE REVIEW

**Review by Dario-DC — COMMENTED** [review]
It looks good :+1:  I left a few comments.

I have a doubt about using CSS property names with and without backticks. I'm okay with not surrounding property names for background color, border, or font size. But sometimes it seems weird to me. For example, border radius, or padding. 

I'm saying this, mainly because there's no accurate translation of those, and I think it might lead to inaccuracies if translated. Of course this may not be true for other languages.

**Comment by ihechikara** [comment]
> It looks good 👍 I left a few comments.
> 
> I have a doubt about using CSS property names with and without backticks. I'm okay with not surrounding property names for background color, border, or font size. But sometimes it seems weird to me. For example, border radius, or padding.
> 
> I'm saying this, mainly because there's no accurate translation of those, and I think it might lead to inaccuracies if translated. Of course this may not be true for other languages.

@Dario-DC, I decided to put most of the property names within backticks. Based on your suggestion, I think that'll make translating them more straightforward. Let me know what you think.

**Review by moT01 — APPROVED** [review]
This looks good @ihechikara 👍 I would be fine it as-is, but here's some suggestions...

Make some of the text of the user stories more flexible - so users don't have to use exact values. For instance, instead of:

``A `margin-bottom` of `10px`.``, Maybe just `A margin on the bottom.` So people can use a value they want.

It's not necessary to change though, just mentioning it. You have several user stories that do allow for some flexible.

I also like `#4`: ``Each `input` and `textarea` element should have their corresponding `label` element with a `for` attribute set to the element `id`.`` I feel like this makes people think about what they have to do more, instead of just copying what they're told to do. For example one says to add ``A `padding` of `10px`.`` - It's fine to have some of these, but it feels like users don't really have to think about that. Again, just mention it - maybe something to keep in mind for future labs.

I would be fine getting this in if you are @ihechikara 👍  Feel free to merge it, or make adjustments if you think some of those should be changed.

**Comment by ihechikara** [comment]
> This looks good @ihechikara 👍 I would be fine it as-is, but here's some suggestions...
> 
> Make some of the text of the user stories more flexible - so users don't have to use exact values. For instance, instead of:
> 
> `` A `margin-bottom` of `10px`. ``, Maybe just `A margin on the bottom.` So people can use a value they want.
> 
> It's not necessary to change though, just mentioning it. You have several user stories that do allow for some flexible.
> 
> I also like `#4`: `` Each `input` and `textarea` element should have their corresponding `label` element with a `for` attribute set to the element `id`. `` I feel like this makes people think about what they have to do more, instead of just copying what they're told to do. For example one says to add `` A `padding` of `10px`. `` - It's fine to have some of these, but it feels like users don't really have to think about that. Again, just mention it - maybe something to keep in mind for future labs.
> 
> I would be fine getting this in if you are @ihechikara 👍 Feel free to merge it, or make adjustments if you think some of those should be changed.

Thanks for the suggestions, @moT01! I've made the user stories more flexible. Just wondering - should I do the same with `#3` in the user stories? Let me know what you think.

**Comment by moT01** [comment]
LGTM 👍

**Pull request merged**
