### PR TITLE
feat: first draft of Rothko CSS project instructions

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Rough draft of the Rothko project.

For issue https://github.com/freeCodeCamp/CurriculumExpansion/issues/131

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
I wonder if it would be better to put the challenge text in the CSS file itself rather than the HTML considering that is where a majority of the code changes are happening. We can make the HTML changes for the students automatically and let them only have to worry about editing the CSS file.

**Comment by scissorsneedfoodtoo** [comment]
@Ethan-Arrowood, yes, very good point! I'll go through the files and fix that.

**Comment by scissorsneedfoodtoo** [comment]
@beaucarnes, thank you for your review! Yes, that's a very good point. I'll look into adding both a description and diagram of the box model at the beginning of the project.

**Comment by scissorsneedfoodtoo** [comment]
@Ethan-Arrowood and @beaucarnes, sorry, my earlier push was rejected because I should have force pushed instead. The new diagrams and descriptions should be there now. Please take a look when you can!

**Comment by beaucarnes** [comment]
Interesting method to have users put the img url in to see the image. I like it.

**Comment by scissorsneedfoodtoo** [comment]
Thanks! I thought about building it out in HTML and CSS, but thought it would be misleading since you can't set apply background color to padding.

**Comment by scissorsneedfoodtoo** [comment]
Will merge this now just to clear the docket. Please leave a comment in #131 if you notice any issues!

**Pull request merged**
