### PR TITLE
feat: balance sheet

### PR DESCRIPTION
**Pull request by nhcarrigan**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

Prototype ready for review!

### CODE REVIEW

**Review by ShaunSHamilton — COMMENTED** [review]
If this PR is just to get the ball rolling, that is fine.

However, this project needs:
1) To look the part - get a touch of @ahmadabdolsaheb 
2) To cover `[attribute]` selector
3) To cover `elem + elem` selector

This project is more than half way into the certification, and should not downgrade in style compared to the previous projects.

**Comment by nhcarrigan** [comment]
> To look the part

Yes I am definitely not an artist 😅 

> To cover [attribute] selector

Covered by https://github.com/freeCodeCamp/CurriculumExpansion/pull/310/files#diff-ad0a310535a2709425ff3df633b62c905641c0c47f802930e36a0240167f6471R81? 

> To cover elem + elem selector

Missed one smh

**Comment by ahmadabdolsaheb** [comment]
awesome, let me know when all are included so I could take a quick look.

**Comment by nhcarrigan** [comment]
Alright @ahmadabdolsaheb this is ready for your expert touch 🙂

**Comment by nhcarrigan** [comment]
@ahmadabdolsaheb I took a look at the changes you were working on in CodePen - looks much better than what I had. I went ahead and migrated them here 🙂

**Comment by ahmadabdolsaheb** [comment]
Thanks for iterating on this project.
The follwoing styles are not showing up, other than that it looks great.
```
.row:nth-child(even) {
  background-color: #f5f6f7;
}
```

**Comment by nhcarrigan** [comment]
> The following styles are not showing up, other than that it looks great.

Thanks for catching that. Looks like the shift in the HTML structure broke the selector. I tweaked it to fix the issue, and this'll be another good opportunity for further explanation in the curricular content. 😁

**Comment by ahmadabdolsaheb** [comment]
Thanks for taking care of it. It seems like we could replace #f5f6f7 with  #d0d0d5 in the last commit for more visibility. Other than that LGMT.

**Comment by ahmadabdolsaheb** [comment]
Also let's get a second opinion on this: @scissorsneedfoodtoo, do you think this balance sheet needs further styling? ( are the sections are blending together?)

**Comment by scissorsneedfoodtoo** [comment]
Hey all, sorry, just seeing this now.

The demo @ahmadabdolsaheb posted above looks great. It seems to cover quite a few advanced selectors, including the ones mentioned above.

One thing I noticed is that, while the color for most text is `#0a0a23`, some things like the `h1`, several `h2`, `span`, and `footer` elements are all set to the default `#000000`. But black and `#0a0a23` are so close that it probably doesn't matter.

If we want to set the color of most text to `#0a0a23`, it might be easier to do that in the `body` rule, and then set specific colors with other selectors. `#0a0a23` also should provide enough contrast against the other background colors (white, light blue, and the two shades of gray).

Also, the `footer` element is outside the closing `</body>` tag. If that's moved inside the `body` element, and `color` is set to `#0a0a23` in the `body` rule, we shouldn't need another selector to adjust to color of the `footer`.

Here's a fork of @ahmadabdolsaheb's pen posted above: https://codepen.io/scissorsneedfoodtoo/pen/XWayxzG

In it, `#0a0a23` is set as the base color for most text, and I tried to clean up some declarations / rules that didn't seem to affect anything.

But feel free to disregard these comments. Some of the things I changed in my pen might be there to teach important concepts that I didn't consider.

**Comment by ahmadabdolsaheb** [comment]
@nhcarrigan, @scissorsneedfoodtoo's version LGMT. Feel free to proceed if LGTU.

**Comment by nhcarrigan** [comment]
Awesome - will pull down those changes, merge this in, and start working on the steps today.
Thanks @ahmadabdolsaheb and @scissorsneedfoodtoo for all the help with this. 💜

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Pull request merged**
