### PR TITLE
chore: adding student table workshop

### LINKED ISSUE #388: chore: add workshop for teaching tables in frontend cert
This will be the second workshop in the HTML forms and tables module in the frontend cert

### PR DESCRIPTION
**Pull request by jdwilkin4**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #388

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
This looks good 👍 Here's some things I found that we could potentially add:

"Improve accessibility by adding `scope` attributes to the `<th>` elements to specify that they are headers for their respective columns" e.g:

```
<th scope="col">Last Name</th>
<th scope="col">First Name</th>
<th scope="col">Grade</th>
```

We could add some styling via the attributes...

```
<table border="1" cellspacing="0" cellpadding="8" width="50%">

<thead bgcolor="#ccc">
```

Screenshot 2024-07-01 at 3 04 24 PM

**Comment by jdwilkin4** [comment]
I like how the styles look but I am on the fence about using inline styles because we will need to be super careful about messaging.
So we will probably need to add a note in the steps for adding inline styles that while inline styles are an option, usually it is better to use an external stylesheets for seperation of concerns reasons.

**Comment by moT01** [comment]
We definitely don't have to add them - but I these are different from inline styles, they are actual table element attributes.

**Comment by jdwilkin4** [comment]
It looks like these attributes are deprecated according to MDN
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement/border
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement/cellPadding
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement/cellSpacing

**Comment by jdwilkin4** [comment]
we could add a style element and add some internal styles for the heading styles

**Comment by moT01** [comment]
> these attributes are deprecated

Nice catch. Yea, if they're deprecated, we probably shouldn't use them.

> we could add a style element

So, style code that wouldn't be visible to the user? I'm not sure I really like that cause it could be confusing. If they go create a table elsewhere, they won't know why it doesn't look good.

**Review by moT01 — APPROVED** [review]
Going to approve this. Feel free to add more if you think it's appropriate @jdwilkin4.

**Pull request merged**
